apiVersion: v1
kind: Service
metadata:
    name: #{var-service}#
    namespace: #{var-namespace}#
    labels:
      app: #{var-service}#
spec:
    selector:
        app: #{var-pod}#
    type: ClusterIP
    ports:
    - port: #{var-port}#
      targetPort: #{var-app-port}#