export enum HttpHeaders {
    // Standard headers
    CONTENT_TYPE = 'content-type',
    ACCEPT = 'accept',
    CONTENT_LENGTH = 'content-length',
    TRANSFER_ENCODING = 'transfer-encoding',
    ACCEPT_LANGUAGE = 'accept-language',
    AUTHORIZATION = 'authorization',
    USER_AGENT = 'user-agent',
    HOST = 'host',
    CONNECTION = 'connection',
    CACHE_CONTROL = 'cache-control',
    ACCEPT_ENCODING = 'accept-encoding',
    ORIGIN = 'origin',
    REFERER = 'referer',
    COOKIE = 'cookie',
    SET_COOKIE = 'set-cookie',
    // Common headers
    X_CORRELATION_ID = 'x-correlation-id',
    X_REQUEST_ID = 'x-request-id',
    OCP_APIM_SUBSCRIPTION_KEY = 'ocp-apim-subscription-key',
    NOMBRE_APLICACION = 'nombreaplicacion',
    PROCESO_NEGOCIO = 'procesonegocio',
    USUARIO_APLICACION = 'usuarioaplicacion',
}
